site_name: Informatica per SIA
site_description: Libro di informatica per il percorso SIA

theme:
  name: material
  language: it
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Passa al tema scuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Passa al tema chiaro
  features:
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - Capitolo 5 - SQL: capitolo-5.md
  - Capitolo 7 - Le reti di computer: capitolo-7.md

plugins:
  - search:
      lang: it
